name: Build Docker Image

on:
  push:
    branches: [ release ]  # 触发分支

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  # Dockerfile 所在目录
          push: true  # 是否推送镜像
          tags: zhijuan/sillytavern-fork:latest
